// Singa: 100 most popular karaoke songs in the United States, 2026.
// Ranked from real US karaoke plays over the preceding 12 months.
const KARAOKE_LEGENDS = [
  ["Sweet Caroline", "Neil Diamond"],
  ["Lose Control", "Teddy Swims"],
  ["Tennessee Whiskey", "Chris Stapleton"],
  ["Creep", "Radiohead"],
  ["Take On Me", "A-ha"],
  ["Pink Pony Club", "Chappell Roan"],
  ["Before He Cheats", "Carrie Underwood"],
  ["Golden", "HUNTR/X"],
  ["Take Me Home, Country Roads", "John Denver"],
  ["I Want It That Way", "Backstreet Boys"],
  ["I Will Survive", "Gloria Gaynor"],
  ["Party In The U.S.A.", "Miley Cyrus"],
  ["In The End", "Linkin Park"],
  ["WAP", "Cardi B"],
  ["Neon Moon", "Brooks & Dunn"],
  ["Dancing Queen", "ABBA"],
  ["Baby", "Justin Bieber"],
  ["Santeria", "Sublime"],
  ["Picture", "Kid Rock"],
  ["What's Up?", "4 Non Blondes"],
  ["Valerie", "Amy Winehouse"],
  ["Friends In Low Places", "Garth Brooks"],
  ["Love", "Keyshia Cole"],
  ["Love Shack", "B-52's"],
  ["Dreams", "Fleetwood Mac"],
  ["Can't Help Falling In Love", "Elvis Presley"],
  ["Zombie", "Cranberries"],
  ["Last Christmas", "Wham!"],
  ["Piano Man", "Billy Joel"],
  ["You Oughta Know", "Alanis Morissette"],
  ["A Million Dreams", "Hugh Jackman"],
  ["Mr. Brightside", "Killers"],
  ["Let It Go", "Idina Menzel"],
  ["Fly Me To The Moon", "Frank Sinatra"],
  ["Teenage Dirtbag", "Wheatus"],
  ["Crazy", "Patsy Cline"],
  ["I Write Sins Not Tragedies", "Panic! At The Disco"],
  ["Bring Me To Life", "Evanescence"],
  ["No Scrubs", "TLC"],
  ["I Wanna Dance With Somebody (Who Loves Me)", "Whitney Houston"],
  ["Unwritten", "Natasha Bedingfield"],
  ["My Way", "Frank Sinatra"],
  ["(Sittin' On) The Dock Of The Bay", "Otis Redding"],
  ["Rolling In The Deep", "Adele"],
  ["Wonderwall", "Oasis"],
  ["Ring Of Fire", "Johnny Cash"],
  ["Something In The Orange", "Zach Bryan"],
  ["Choosin' Texas", "Treaty Oak Revival"],
  ["Wagon Wheel", "Darius Rucker"],
  ["Baby Got Back", "Sir Mix-a-Lot"],
  ["Jolene", "Dolly Parton"],
  ["Livin' On A Prayer", "Bon Jovi"],
  ["Misery Business", "Paramore"],
  ["Your Man", "Josh Turner"],
  ["Careless Whisper", "George Michael"],
  ["Landslide", "Fleetwood Mac"],
  ["Iris", "Goo Goo Dolls"],
  ["Man I Need", "Olivia Dean"],
  ["Strawberry Wine", "Deana Carter"],
  ["...Baby One More Time", "Britney Spears"],
  ["If I Ain't Got You", "Alicia Keys"],
  ["Stay", "Rihanna"],
  ["Kryptonite", "3 Doors Down"],
  ["Bohemian Rhapsody", "Queen"],
  ["All Of Me", "John Legend"],
  ["Shallow", "Lady Gaga"],
  ["Don't Stop Believin'", "Journey"],
  ["Santa Baby", "Eartha Kitt"],
  ["Mama's Broken Heart", "Miranda Lambert"],
  ["Under The Bridge", "Red Hot Chili Peppers"],
  ["Since U Been Gone", "Kelly Clarkson"],
  ["White Christmas", "Bing Crosby"],
  ["Tequila", "Champs"],
  ["Need You Now", "Lady A"],
  ["Have You Ever Seen The Rain?", "Creedence Clearwater Revival"],
  ["From The Start", "Laufey"],
  ["A Whole New World", "Lea Salonga"],
  ["Hallelujah", "Jeff Buckley"],
  ["Goodbye Earl", "Chicks"],
  ["New York, New York", "Frank Sinatra"],
  ["Back To Black", "Amy Winehouse"],
  ["When I Was Your Man", "Bruno Mars"],
  ["Feeling Good", "Michael Buble"],
  ["Crazy Rap", "Afroman"],
  ["Ain't No Mountain High Enough", "Marvin Gaye"],
  ["Bad Romance", "Lady Gaga"],
  ["Take It Easy", "Eagles"],
  ["When We Were Young", "Adele"],
  ["At Last", "Etta James"],
  ["My Own Worst Enemy", "Lit"],
  ["All The Small Things", "Blink-182"],
  ["Ironic", "Alanis Morissette"],
  ["Como La Flor", "Selena"],
  ["Lips Of An Angel", "Hinder"],
  ["The Climb", "Miley Cyrus"],
  ["Let Me Love You", "Mario"],
  ["Ain't It Fun", "Paramore"],
  ["Closing Time", "Semisonic"],
  ["A Thousand Miles", "Vanessa Carlton"],
  ["Still Into You", "Paramore"]
];
